import { CityPolicy } from '../types';

export const CITIES: CityPolicy[] = [
  {
    cityId: 'shanghai',
    cityName: '上海',
    avgSalary: 12183,
    baseMin: 7310,
    baseMax: 36549,
    medicalMinYearsMale: 15,
    medicalMinYearsFemale: 15,
    unemploymentBenefit: 2175,
  },
  {
    cityId: 'beijing',
    cityName: '北京',
    avgSalary: 11537,
    baseMin: 6385,
    baseMax: 33891,
    medicalMinYearsMale: 25,
    medicalMinYearsFemale: 20,
    unemploymentBenefit: 2124,
  },
  {
    cityId: 'guangzhou',
    cityName: '广州',
    avgSalary: 10449,
    baseMin: 5284,
    baseMax: 26421,
    medicalMinYearsMale: 25,
    medicalMinYearsFemale: 20,
    unemploymentBenefit: 2070,
  },
  {
    cityId: 'shenzhen',
    cityName: '深圳',
    avgSalary: 10725,
    baseMin: 6000,
    baseMax: 26421,
    medicalMinYearsMale: 25,
    medicalMinYearsFemale: 25,
    unemploymentBenefit: 2124,
  },
  {
    cityId: 'hangzhou',
    cityName: '杭州',
    avgSalary: 9210,
    baseMin: 4462,
    baseMax: 22311,
    medicalMinYearsMale: 20,
    medicalMinYearsFemale: 20,
    unemploymentBenefit: 1824,
  },
];
